[model]
model_name = 'EVA02-B-16'
pretrained = 'merged2b_s8b_b131k'
precision = 'amp' # amp, amp_bf16, amp_bfloat16
# resume = 'logs/24-11-20_18-31-25_EVA02-B-16/checkpoint/epoch_12.pt'
save_frequency = 1
# max_save_count = 10

[tokenizer]
weighted_shuffle = false
gaussian_params = ["mu_p=0.7", "sigma_p=0.2", "scale=3", "min_offset=2.0"]

[train]
seed = 42
epochs = 20
batch_size = 16
accum_freq = 4
loss_fn = "KL"

[validation]
valid = true
valid_batch_size = 24
valid_size = 3000
recall = true
split_by_class = true

[logger]
report_to = 'wandb'    # tensorboard, wandb
wandb_project_name = 'tag-clip' #
# run_id = 't724iq04'

[optimizer]
image_encoder_lr = 2e-4
text_encoder_lr = 2e-5
warmup = 500
wd = 0.05
beta1 = 0.9
beta2 = 0.98
esp = 1e-6
img_lwld_decay = 0.75   # 0.75
text_lwld_decay = 0.75  # 0.75

[data]
train = 'my_dataset/table_data/24-11-14_20-05-27_processed.parquet'
image_key = 'image_path'
tag_key = 'tags'
workers = 4
cache_dir = './my_dataset/experiment/img_caches'
cache_image = true
save_cache_image = true
cache_load = true
cache_load_disk = true

[dataset]
dynamic_img_size = true
image_size = [448, 448] # [512, 512], 448
patch_size = 16
step_size = 64
min_size=210
max_size=840

[debug]
debug = false